openapi: 3.0.0
info:
  description: "This is a documentation for [covid-19-api](https://github.com/cyrilgavala/covid-19-api)."
  version: 4.0.0
  title: Covid-19-API
  contact:
    email: cyril.gavala@gmail.com
  license:
    name: MIT licence
    url: https://github.com/cyrilgavala/covid-19-api/blob/main/LICENSE
tags:
  - name: stats
    description: Basic Covid-19 data statistics
  - name: series
    description: Various series of Covid-19 data
paths:
  /stats/day:
    get:
      tags:
        - stats
      summary: Find statistics for particular day
      parameters:
        - name: date
          in: query
          description: Day which data are requested for
          required: true
          explode: true
          example: "2021-03-10T00:00:00.000Z"
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/DailyData"
        "400":
          description: Missing day parameter
          content:
            application/json:
              schema:
                type: object
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal server error
  /series/deaths:
    get:
      tags:
        - series
      summary: Get series of deaths data
      parameters:
        - name: startDate
          in: query
          description: Start day which data are requested for
          example: "2021-03-10T00:00:00.000Z"
          required: false
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DeathsSeries"
        "500":
          description: Internal server error
  /series/positivePercentage:
    get:
      tags:
        - series
      summary: Get series of positive percentage data
      parameters:
        - name: startDate
          in: query
          description: Start day which data are requested for
          example: "2021-03-10T00:00:00.000Z"
          required: false
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/PercentageSeries"
        "500":
          description: Internal server error
  /series/testsDaily:
    get:
      tags:
        - series
      summary: Get series of daily tests data
      parameters:
        - name: startDate
          in: query
          description: Start day which data are requested for
          example: "2021-03-10T00:00:00.000Z"
          required: false
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyTestsSeries"
        "500":
          description: Internal server error
  /series/deathsDaily:
    get:
      tags:
        - series
      summary: Get series of daily deaths data
      parameters:
        - name: startDate
          in: query
          description: Start day which data are requested for
          example: "2021-03-10T00:00:00.000Z"
          required: false
          explode: true
          schema:
            type: string
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/DailyDeathsSeries"
        "500":
          description: Internal server error
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://covid-19-api.herokuapp.com
components:
  schemas:
    DailyData:
      type: object
      properties:
        date:
          type: string
          format: date-time
          example: "2021-03-10T00:00:00.000Z"
        confirmed:
          type: number
          format: int64
          example: 500
        deaths:
          type: number
          format: int64
          example: 100
        numberOfTests:
          type: number
          format: int64
          example: 10000
    DeathsSeries:
      type: object
      properties:
        deaths:
          type: number
          format: int64
          example: 100
        date:
          type: string
          format: date-time
          example: "2021-03-10T00:00:00.000Z"
    PercentageSeries:
      type: object
      properties:
        percentage:
          type: number
          format: int64
          example: 15.75
        date:
          type: string
          format: date-time
          example: "2021-03-10T00:00:00.000Z"
    DailyTestsSeries:
      type: object
      properties:
        tests:
          type: number
          format: int64
          example: 100000
        confirmed:
          type: number
          format: int64
          example: 1000
        date:
          type: string
          format: date-time
          example: "2021-03-10T00:00:00.000Z"
    DailyDeathsSeries:
      type: object
      properties:
        deaths:
          type: number
          format: int64
          example: 100
        date:
          type: string
          format: date-time
          example: "2021-03-10T00:00:00.000Z"
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: "Error message"